### ISSUE TITLE
Precision at the end of section 14.5

### ISSUE THREAD

**Issue by jcornickm** [rafalab/dsbook-part-2#14]
The first sentence in the next to last paragraph states:  "The regression line is therefore much more stable than the conditional mean".  This is not quite correct.  The regression line is a way of computing the (linear) conditional expected value.  This is important to avoid the rather frequent mistake of assuming that multivariate regression can be used to prover causation, rather than (linear) conditional expectations.  Goldberg (A Course in Econometrics) makes this point more clearly than any other text I have consulted (not that I have consulted many econometric textbooks).

**Comment by rafalab** [comment]
I can change it to "The prediction obtained the regression line is therefore much more stable than the prediction obtained using the conditional mean." . Do you think this avoids the confusion? Note that the next paragraph explains that lower variance is not always preferable (due to potential bias):

> So why not always use the regression for prediction? Because it is not always appropriate. For example, Anscombe provided cases for which the data does not have a linear relationship. 

Happy to hear your thoughts before making an edit.

**Comment by rafalab** [comment]
Thank you for the feedback! It's timely as I'm currently working on the second edition.

As you probably noticed, we've split the original book into two parts. The second edition of the first part is already published, and I believe the R explanations are clearer there. In the second part, we aim to focus more on statistical thinking rather than R code. It might be a good idea to be more explicit about the need for prior knowledge of R to fully benefit from it. Any further thoughts appreciated.

**Comment by jcornickm** [comment]
Well, exactly.

This makes a lot of sense to me
